# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

from Core import Request, Response
from .    import home_router

@home_router.get("/robots.txt")
async def robots_txt(request: Request):
    """robots.txt - Arama motoru botları için yönergeler"""

    robots = f"""# robots.txt for webApp
# Generated by KekikAkademi

# All bots welcome, except for paths listed below
User-agent: *
Allow: /
Disallow: /api/
Disallow: /wss/
Disallow: /admin/

# Sitemaps
Sitemap: https://{request.url.netloc}/sitemap.xml

# Specific bot rules
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: Bingbot
Allow: /
"""

    return Response(
        content    = robots,
        media_type = "text/plain; charset=utf-8",
        headers    = {
            "Cache-Control" : "public, max-age=86400",
            "X-Robots-Tag"  : "noindex"
        }
    )


@home_router.get("/.well-known/security.txt")
@home_router.get("/security.txt")
async def security_txt(request: Request):
    """security.txt - Güvenlik açıklarını bildirmek için iletişim bilgileri"""

    security = f"""# Security Policy for webApp

Contact: mailto:keyiflerolsun@gmail.com
Expires: {str(__import__('datetime').datetime.now(__import__('datetime').timezone.utc) + __import__('datetime').timedelta(days=365))[:10]}T23:59:59.000Z
Preferred-Languages: tr, en
Canonical: https://{request.url.netloc}/.well-known/security.txt

# Güvenlik açığı bildirimi için lütfen yukarıdaki e-posta adresini kullanın.
# Security vulnerability reports should be sent to the email above.
"""

    return Response(
        content    = security,
        media_type = "text/plain; charset=utf-8",
        headers    = {
            "Cache-Control" : "public, max-age=86400",
            "X-Robots-Tag"  : "noindex"
        }
    )


@home_router.get("/humans.txt")
async def humans_txt():
    """humans.txt - Site hakkında insan dostu bilgiler"""

    humans = """/* TEAM */
Developer: @keyiflerolsun
GitHub: https://github.com/keyiflerolsun
Location: Istanbul, Turkey

/* SITE */
Name: webApp
Description: Modern FastAPI Web Application
Latest Update: 2025-11-05
Standard: HTML5, CSS3, JavaScript (ES6+)
Tools: Visual Studio Code, Git

/* TECH STACK */
Backend Framework: FastAPI (Python 3.13+)
Server: Uvicorn + Gunicorn
Database: MongoDB
Cache Layer: Redis
Real-time Communication: WebSocket
Frontend: Vanilla JavaScript
Styling: CSS3, Glassmorphism Design
Icons: Font Awesome 6

/* CONTACT & SOCIAL */
GitHub: https://github.com/keyiflerolsun
Email: Check GitHub profile
Website: Check GitHub profile

/* LICENSE & CREDITS */
Built with FastAPI Framework
Developed by @keyiflerolsun
All rights reserved © 2025
"""

    return Response(
        content    = humans,
        media_type = "text/plain; charset=utf-8",
        headers    = {
            "Cache-Control" : "public, max-age=86400",
            "X-Robots-Tag"  : "noindex, nofollow"
        }
    )
